# Group pmtoapib example

Example collection for pmtoapib


## users [/users{?page,per_page}]

### users [GET]

Get a list of all users

+ Parameters

    + page (string, required) - DESCRIPTION
    + per_page (string, required) - DESCRIPTION
    
+ Request

    + Headers
            
            Authorization: Bearer {{access_token}}
    

+ Response 200 (application/json)

    + Headers
            
            Content-Length: 185
            Date: Wed, 22 Mar 2017 11:15:37 GMT

    + Body

            <!-- include(responses/get-200-users.json) -->





## user [/users/2]

### user [GET]

Get a specific user

+ Request

    + Headers
            
            Authorization: Bearer {{access_token}}
    

+ Response 200 (application/json)

    + Headers
            
            Content-Length: 59
            Date: Wed, 22 Mar 2017 11:16:25 GMT

    + Body

            <!-- include(responses/users/get-200_userID_2-2.json) -->

+ Response 404 (application/json)

    + Headers
            
            Content-Length: 39
            Date: Wed, 22 Mar 2017 11:16:02 GMT

    + Body

            <!-- include(responses/users/get-404_userID_1-2.json) -->





## me [/me]

### me [GET]

Get information about the authenticated user

+ Request

    + Headers
            
            Authorization: Bearer {{access_token}}
    

+ Response 200 (application/json)

    + Headers
            
            Content-Length: 77
            Date: Wed, 22 Mar 2017 11:16:58 GMT

    + Body

            <!-- include(responses/get-200-me.json) -->





## me edit [/me]

### me edit [POST]

Edit information about the authenticated user

+ Request

    + Headers
            
            Authorization: Bearer {{access_token}}
            Content-Type: application/json
    
    + Body

    	    {
				"name": "Phillipp",
				"twitter_profile": "PhillippOh"
			}
    

+ Response 200 (application/json)

    + Headers
            
            NAME: VALUE

    + Body

            <!-- include(responses/post-200-me.json) -->





